#!/usr/bin/env bash
destination="slides/talk-jekyll-algolia-show-and-tell/"
npm run build &&
rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  ./public/* \
  pixelastic:/var/www/talks.pixelastic.com/$destination && \
  echo "http://talks.pixelastic.com/$destination"

